<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="tarun" name="Marketplace.PurchaseBundleOffline" tests="8" failures="0" timestamp="25 Sep 2020 05:40:22 GMT" time="155.306" errors="1">
  <testcase name="purchaseBundleOffline" time="40.415" classname="Marketplace.PurchaseBundleOffline"/>
  <testcase name="payPendingOrderPayment" time="93.962" classname="Marketplace.PurchaseBundleOffline"/>
  <testcase name="verifyInvoiceAmountInMyledger" time="1.135" classname="Marketplace.PurchaseBundleOffline"/>
  <testcase name="verifyReceiptAmountInMyBilling" time="1.063" classname="Marketplace.PurchaseBundleOffline"/>
  <testcase name="verifyTotalAmountInMyInvoices" time="7.834" classname="Marketplace.PurchaseBundleOffline"/>
  <testcase name="verifyEmailServiceEmailLogs" time="0.034" classname="Marketplace.PurchaseBundleOffline"/>
  <testcase name="verifyTotalAmountInMyReceipts" time="7.053" classname="Marketplace.PurchaseBundleOffline"/>
  <testcase name="verifyAcronisServiceEmailLogs" time="3.810" classname="Marketplace.PurchaseBundleOffline">
    <error type="java.lang.AssertionError" message="Your Acronis Account is not set up expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Your Acronis Account is not set up expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at Marketplace.PurchaseBundleOffline.verifyAcronisServiceEmailLogs(PurchaseBundleOffline.java:317)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyAcronisServiceEmailLogs -->
</testsuite> <!-- Marketplace.PurchaseBundleOffline -->
