<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="tarun" name="Marketplace.PurchaseMSOffice365Online" tests="18" failures="0" timestamp="8 Dec 2020 09:54:35 GMT" time="179.229" errors="3">
  <testcase name="verifyReceiptAmountInMyAdmin" time="0.871" classname="Marketplace.PurchaseMSOffice365Online"/>
  <testcase name="verifyInvoiceAmountInMyAdmin" time="0.053" classname="Marketplace.PurchaseMSOffice365Online"/>
  <testcase name="verifyInvoiceAmountInMyledger" time="1.209" classname="Marketplace.PurchaseMSOffice365Online"/>
  <testcase name="verifyReceiptAmountInMyBilling" time="1.193" classname="Marketplace.PurchaseMSOffice365Online"/>
  <testcase name="purchaseOrder" time="120.162" classname="Marketplace.PurchaseMSOffice365Online"/>
  <testcase name="verifyTotalAmountInMyOrders" time="0.075" classname="Marketplace.PurchaseMSOffice365Online"/>
  <testcase name="verifyOrderInMyAccount" time="10.265" classname="Marketplace.PurchaseMSOffice365Online"/>
  <testcase name="verifyReceiptNumberInMyAdmin" time="0.047" classname="Marketplace.PurchaseMSOffice365Online"/>
  <testcase name="verifyInvoiceStatusInMyAdmin" time="0.869" classname="Marketplace.PurchaseMSOffice365Online"/>
  <testcase name="verifyServiceStatusInMyAdmin" time="8.911" classname="Marketplace.PurchaseMSOffice365Online">
    <error type="java.lang.AssertionError" message="expected [Active] but found [Pending]">
      <![CDATA[java.lang.AssertionError: expected [Active] but found [Pending]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Marketplace.PurchaseMSOffice365Online.verifyServiceStatusInMyAdmin(PurchaseMSOffice365Online.java:408)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyServiceStatusInMyAdmin -->
  <testcase name="verifyOrderStatusInMyAdmin" time="0.806" classname="Marketplace.PurchaseMSOffice365Online"/>
  <testcase name="verifyLedgerAmountInMyAdmin" time="3.915" classname="Marketplace.PurchaseMSOffice365Online"/>
  <testcase name="verifyOrderAmountInMyBilling" time="7.614" classname="Marketplace.PurchaseMSOffice365Online"/>
  <testcase name="verifyOrderAmountInMyAdmin" time="0.038" classname="Marketplace.PurchaseMSOffice365Online"/>
  <testcase name="verifyTotalAmountInMyInvoices" time="9.447" classname="Marketplace.PurchaseMSOffice365Online"/>
  <testcase name="verifyEmailLogs" time="3.922" classname="Marketplace.PurchaseMSOffice365Online">
    <error type="java.lang.AssertionError" message="Your Office 365 Account is not set up expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Your Office 365 Account is not set up expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at Marketplace.PurchaseMSOffice365Online.verifyEmailLogs(PurchaseMSOffice365Online.java:386)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyEmailLogs -->
  <testcase name="verifyTotalAmountInMyReceipts" time="9.008" classname="Marketplace.PurchaseMSOffice365Online"/>
  <testcase name="verifyEmailLogsInMyAdmin" time="0.824" classname="Marketplace.PurchaseMSOffice365Online">
    <error type="java.lang.AssertionError" message="Your Office 365 Account is not set up expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Your Office 365 Account is not set up expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at Marketplace.PurchaseMSOffice365Online.verifyEmailLogsInMyAdmin(PurchaseMSOffice365Online.java:518)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyEmailLogsInMyAdmin -->
</testsuite> <!-- Marketplace.PurchaseMSOffice365Online -->
